fix

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -13,15 +13,20 @@ jobs:
             # Store Conjur Token in temp file
             RESPONSE_CODE=$(curl -s -w "%{http_code}" -o /tmp/token.txt -k --request POST "$CONJUR_FQDN/authn-jwt/$CONJUR_AUTHN_ID/$CONJUR_ORG/authenticate" --header 'Content-Type: application/x-www-form-urlencoded' --header "Accept-Encoding: base64" --data-urlencode "jwt=$CIRCLE_OIDC_TOKEN")
             TOKEN=$(cat /tmp/token.txt)
-            echo $RESPONSE_CODE
-            [ "$RESPONSE_CODE" != "200" ] && echo "Authentication failed"; exit 1
+            if [ "$RESPONSE_CODE" != "200" ]; then
+              echo "Autentication Failed"
+              exit 1
+            fi
             echo "export TOKEN=$TOKEN" >> "$BASH_ENV"
       - run:
           name: "Consuming secret from Conjur"
           command: |
              RESPONSE_CODE=$(curl -s -w "%{http_code}" -o /tmp/secret.txt -k -X GET -H "Authorization: Token token=\"$TOKEN\"" "$CONJUR_FQDN/secrets/$CONJUR_ORG/variable/circleci/apps/safe/secret1")
              SECRET=$(cat /tmp/secret.txt)
-             [ "$RESPONSE_CODE" != "200" ] && echo "Secret retrieval failed"; exit 1
+             if [ "$RESPONSE_CODE" != "200" ]; then
+              echo "Secret retrieval failed"
+              exit 1
+             fi
              echo "export SECRET=$SECRET" >> "$BASH_ENV"
       - run:
           name: "Print secret"
